import { createSlice } from '@reduxjs/toolkit';
// import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';



export const storeSlice = createSlice({

  name: 'store',

  initialState: {

		// trucks with load waiting in line for unload
		queue: [

			{ id: 1, type: 's', cover: true, 
				pallets: [{id:'p13', c:'red'}] },

			{ id: 2, type: 'm', cover: true, 
				pallets: [{id:'p11', c:'pink'}, {id:'p12', c:'blue'}] },

			{ id: 3, type: 'xl', cover: true, 
				pallets: [{id:'p9', c:'pink'}, {id:'p10', c:'green'}] }
		],


		// ramps either as store zones and place for trucks
		ramps: [

			{ no: 0, pallets: [], 
				truck: {} },

			{ no: 1, pallets: [], 
				truck: {} },

			{ no: 2, pallets: [], 
				truck: {} },
		],


		// store zones with pallets
		zones: [

			{ no: 0, 
				pallets: [
					{id:'p1', c:'red'}, 
					{id:'p2', c:'orange'}, 
					{id:'p7', c:'white'}, 
					{id:'p6', c:'purple'}, 
				] 
			},

			{ no: 1, pallets: [] },

			{ no: 2, 
				pallets: [
					{id:'p4', c:'black'}, 
					{id:'p5', c:'green'}
				] 
			},

			{ no: 3, 
				pallets: [ {id:'p8', c:'blue'} ] 
			},

			{ no: 4, pallets: [] },
			{ no: 5, pallets: [] },
			{ no: 6, pallets: [] },
			{ no: 7, pallets: [] },
		],
	},


  // REDUCERS 
  reducers: {

    addTruck: (state, payload) => {
			state.queue.push( payload.payload )
		},

    removeTruck: (state, payload) => {
			let id = Number( payload.payload.id )
			let remIndex = state.queue.findIndex( inx => inx.id === id )
			state.queue.splice(remIndex, 1)
		},

		remove: (state, payload) => {
			let name = payload.payload.name
			let index = payload.payload.index
			let id = payload.payload.id

			if (name === "field") {
				let rmIndex = state.fields[index].pallets.findIndex( inx => inx.id === id )
				state.fields[index].pallets.splice(rmIndex, 1)
			}

			if (name === "ramp") {
				let rmIndex = state.ramps[index].pallets.findIndex( inx => inx.id === id )
				state.ramps[index].pallets.splice(rmIndex, 1)
			}

			if (name === "truck") {
				// index is useless here
				// console.log("indeks rampy",index, "szukam id",id,"w",JSON.stringify(state.ramps[index].truck.pallets ) )

				let truIndex = 0
				let rmIndex = state.ramps[truIndex].truck.pallets.findIndex( inx => inx.id === id )
				state.ramps[truIndex].truck.pallets.splice(rmIndex, 1)
			}
		},
							 
		add: (state, payload) => {
			let name = payload.payload.name
			let index = payload.payload.index
			// payload iz pellet or truck
			let object = payload.payload.pellet

			if (name === "field") {
				state.fields[index].pallets.push( object ) 
			}
			if (name === "ramp") {
				state.ramps[index].pallets.push( object ) 
			}
			if (name === "truck") {
				state.ramps[index].truck.pallets.push( object ) 
			}
			if (name === "extRamp") {
				state.ramps[index].truck = object 
			  // todo
				//console.log( JSON.stringify(state) )
			}
		},

    dump: (state) => {
			console.log("ALL", JSON.stringify(state, null, 2) )
		},

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});


//export const selectCount = (state) => state.counter

export const { addTruck, removeTruck, add, remove, dump } = storeSlice.actions;
export default storeSlice.reducer;
